### ISSUE TITLE
Contexts list representation

### ISSUE THREAD

**Issue by SandiCat** [sgraf812/elm-graph#3]
How come I can't get the contexts of a graph like I can get the nodes or the edges? I don't want to map over them, just have a list of them returned. It would make my code simpler in at least two places, and it does not seem like a huge feature. Is this a conscious design decision?

**Comment by sgraf812** [comment]
It was somewhat concious. I imagined that accessing just the contexts is a code smell of some sort, when you actually want to use a fold (`fold`, `dfs` and `bfs` variants). You can still get a hold of the contexts with `contexts = fold (::) []`. 

Maybe this is too complicated? I would add something semantically identical to `contexts` if I could identify the need, so I would like an example where using neither `fold` nor the definition of `contexts` is inconvenient.

**Comment by SandiCat** [comment]
I apologize. I'm still new to functional programming so I'm yet to accustom myself to fold. I forgot about it when I was implementing this functionality. Thank you for clearing things up and sorry for wasting your time.

**Comment by sgraf812** [comment]
No problem, not a waste of time at all :)
