### ISSUE TITLE
defining nodes as a collection 

### ISSUE THREAD

**Issue by dpren** [sgraf812/elm-graph#6]
Do you know if yours or Erwig's library can define nodes as a collection of nodes? Say if you wanted to make Belt a member of Pants. Is that even a thing?

I'm writing a graph library around the Web Audio API which has this OO notion of connecting a node to a node.property

**Comment by sgraf812** [comment]
Hey, you should probably look at [this repo](https://github.com/elm-community/graph), where I currently continue providing support.

Also I'm not sure I understand. Are you saying you want to model sets as nodes, with edges between nodes denoting a subset relationship?

**Comment by dpren** [comment]
Gotcha. 

Im attempting to model this library in Elm:
https://github.com/benji6/virtual-audio-graph/blob/master/README.md

In the Readme they show a node like this:

  1: ['gain', {key: 0, destination: 'frequency'}, {gain: 10}],
  

I've never seen this done in a graph using a language like Elm or Haskell. I'm wondering what the best way to do it is.

**Comment by sgraf812** [comment]
I don't see why elm-graph shouldn't be able to model that. The problem I have with that library is that it extensively makes use of dynamic typing. You would model these things through proper ADTs in Elm, which is more explicit. The end result would look more like

```
updateCommand :: Cmd ()
updateCommand =
  WebAudio.update 
    [ 0 :-> Gain OutputPort [ gain := 0.2 ]
    , 1 :-> SawtoothOscillator (Port 0) [ frequency := 440, startTime := blub, stopTime := blah ]
    , ...
    ]
``` 
(`:->` and `:=` are just some synonyms for pairs or something similar, it's mostly the responsiblity of the `WebAudio.update` implementation to figure things out)

I'm unsure which of the fields are optional and which are not, so there's that...

I'm not even sure you need a full graph library, at least it would obscure the exposed interface, IMO. As long as you don't need any graph algorithms, I wouldn't go through the hassle of building up the graph in the first place.
